directories:
  input: /Users/jaswanth/Jaswanth_Workspace/video_collection
  output: transcripts_generated/

logging:
  level: INFO

processing:
  video_extensions: ['.mp4', '.avi', '.mov', '.mkv']
  audio_extensions: ['.mp3', '.wav', '.m4a']

transcription:
  model: base
  language: en
  use_gpu: false
